### ISSUE TITLE
Current player message still displayed at the end of the game

### ISSUE THREAD

**Issue by atilbian** [marmelab/Hex#11]
![image](https://user-images.githubusercontent.com/99178555/153583688-72d36d99-4492-4f0b-ba67-108a34b08529.png)

**Comment by slax57** [comment]
As pointed out by François, we could just disallow playing on a board this small, since it's no interesting game anyway. This could be easier than trying to fix the overlapping labels issue.

I suggest something like size should be greater or equal to 5. What do you think?

**Comment by atilbian** [comment]
I agree with that, maybe we could even start with a minimum size of 6 because I think that for a size of 5 the white player can always win
